### PR TITLE
add --dist/-d parameter to specify saving directory

### PR DESCRIPTION
**Pull request by FHYQ-Dong**
add --dist/-d parameter in `learn.py` to specify saving directory, set to the current directory by default.

e.g.
```bash
python learn.py -d ./downloads
```

### CODE REVIEW

**Comment by FHYQ-Dong** [comment]
add:
the -d parameter is set to the current directory by default

**Review by erbanku — CHANGES_REQUESTED** [review]
It is recommended to set the default download directory (if not specified) to the current directory, rather than the `downloads` subfolder of the current directory.

**Review by erbanku — COMMENTED** [review]
Do you want to use `~/Downloads` folder or `./Downloads` folder (subfolder of the script located folder)?

**Comment by FHYQ-Dong** [comment]
my bad... i forgot to change the it...

the download directory is now set to the current folder now

**Review by erbanku — APPROVED** [review]

**Review by erbanku — APPROVED** [review]

**Review by Trinkle23897 — APPROVED** [review]

**Pull request merged**
